name: Setup uv
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.10"
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
        python-version: ${{ matrix.python-version }}
